name: Test Runner (release:Cloudflare)

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      ENDPOINT: ${{ secrets.ENDPOINT }}
      REGION: ${{ secrets.REGION }}
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      TOKEN_VALUE: ${{ secrets.TOKEN_VALUE }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create env-cf file
        run: |
          touch .env-cf
          echo ENDPOINT=${{ secrets.ENDPOINT }} >> .env-cf
          echo REGION=${{ secrets.REGION }} >> .env-cf
          echo ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }} >> .env-cf
          echo SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }} >> .env-cf
          echo BUCKET_NAME=${{ secrets.BUCKET_NAME }} >> .env-cf
          echo TOKEN_VALUE=${{ secrets.TOKEN_VALUE }} >> .env-cf

      - name: Run e2e tests
        uses: nick-fields/retry@v3.0.0
        with:
          max_attempts: 3
          retry_on: any
          timeout_minutes: 5
          retry_wait_seconds: 20
          command: npm run test:cloudflare
